### ISSUE TITLE
Project manager issue #2

### ISSUE THREAD

**Issue by Azaezel** [LuisAntonRebollo/Torque3D#28]
When attempting to review the latest revision by creating a fresh project via the torque project manager, it failed to include the requisite references to 

Engine\lib\glew\include\GL\glew.h

**Comment by LuisAntonRebollo** [comment]
Thanks for reporting.

I need more information to solve the problem

Read this guide on how to report problems and add any additional information you find relevant. 
https://github.com/LuisAntonRebollo/Torque3D/wiki/ReportingIssues

**Comment by Azaezel** [comment]
It would appear you resolved this one in the course of correcting https://github.com/LuisAntonRebollo/Torque3D/commit/75085cf981eeedcc3d408f94d7db1a924ddc7023
Not sure I'd have included it in the actual main dll, but it does function.
